/*
    Projeto: ISEEYOU
    Arquivo: 00_drop_all.sql
    Objetivo: remover os objetos do banco em ordem segura para recriação do modelo.
    Banco alvo: SQL Server

    ATENÇÃO: execute somente em ambiente de desenvolvimento/testes.
*/

DROP VIEW IF EXISTS dbo.VW_SY_ASSINATURAS_ATIVAS;
DROP VIEW IF EXISTS dbo.VW_SY_ESTRESSE_GATILHOS;
DROP VIEW IF EXISTS dbo.VW_SY_RESULTADO_TESTE;
DROP VIEW IF EXISTS dbo.VW_SY_RESUMO_SONO;
DROP VIEW IF EXISTS dbo.VW_SY_REGISTROS_DIARIOS;
DROP VIEW IF EXISTS dbo.VW_SY_USUARIO_PERFIL;
GO

DROP TRIGGER IF EXISTS dbo.TR_TB_SY_RESPOSTA_TESTE_USUARIO_VALIDAR_PERGUNTA;
DROP TRIGGER IF EXISTS dbo.TR_TB_SY_APLICACAO_TESTE_VALIDAR_FAIXA;
DROP TRIGGER IF EXISTS dbo.TR_TB_SY_TP_CLASSIFICACAO_VALIDAR_ATUALIZACAO;
DROP TRIGGER IF EXISTS dbo.TR_TB_SY_CLASSIFICACAO_VALIDAR_FAIXA;
GO

DROP TABLE IF EXISTS dbo.TB_SY_A_PERSONALIDADE_CARACTERISTICA;
DROP TABLE IF EXISTS dbo.TB_SY_LINK;
DROP TABLE IF EXISTS dbo.TB_SY_SITUACAO;
DROP TABLE IF EXISTS dbo.TB_SY_FEEDBACK;
DROP TABLE IF EXISTS dbo.TB_SY_A_ESTRESSE_GATILHO;
DROP TABLE IF EXISTS dbo.TB_SY_MNT_ESTRESSE;
DROP TABLE IF EXISTS dbo.TB_SY_MNT_SONO;
DROP TABLE IF EXISTS dbo.TB_SY_REGISTRO_HUMOR;
DROP TABLE IF EXISTS dbo.TB_SY_RESPOSTA_TESTE_USUARIO;
DROP TABLE IF EXISTS dbo.TB_SY_APLICACAO_TESTE;
DROP TABLE IF EXISTS dbo.TB_SY_FAIXA_RESULTADO_TESTE;
DROP TABLE IF EXISTS dbo.TB_SY_A_TESTE_PERGUNTA_TESTE;
DROP TABLE IF EXISTS dbo.TB_SY_PERGUNTA_TESTE;
DROP TABLE IF EXISTS dbo.TB_SY_TESTE;
DROP TABLE IF EXISTS dbo.TB_SY_CLASSIFICACAO;
DROP TABLE IF EXISTS dbo.TB_SY_ASSINATURA;
DROP TABLE IF EXISTS dbo.TB_SY_PSICOLOGO;
DROP TABLE IF EXISTS dbo.TB_SY_PESSOA_FISICA;
DROP TABLE IF EXISTS dbo.TB_SY_USUARIO;
DROP TABLE IF EXISTS dbo.TB_SY_CARACTERISTICA;
DROP TABLE IF EXISTS dbo.TB_SY_PERSONALIDADE;
DROP TABLE IF EXISTS dbo.TB_SY_GATILHOS;
DROP TABLE IF EXISTS dbo.TB_SY_HUMOR;
DROP TABLE IF EXISTS dbo.TB_SY_TP_TESTE;
DROP TABLE IF EXISTS dbo.TB_SY_TP_CLASSIFICACAO;
DROP TABLE IF EXISTS dbo.TB_SY_PLANO;
DROP TABLE IF EXISTS dbo.TB_SY_ENDERECO;
GO
