/*
    Projeto: ISEEYOU
    Arquivo: 02_create_indexes.sql
    Objetivo: criar índices auxiliares para consultas e relatórios.
*/

CREATE INDEX IX_TB_SY_ASSINATURA_ID_USUARIO ON dbo.TB_SY_ASSINATURA (id_usuario);
CREATE INDEX IX_TB_SY_CLASSIFICACAO_TIPO_VALOR ON dbo.TB_SY_CLASSIFICACAO (id_tp_classificacao, vl_classificacao);
CREATE INDEX IX_TB_SY_REGISTRO_HUMOR_USUARIO_DATA ON dbo.TB_SY_REGISTRO_HUMOR (id_usuario, dt_registro);
CREATE INDEX IX_TB_SY_MNT_SONO_USUARIO_INICIO ON dbo.TB_SY_MNT_SONO (id_usuario, dt_inicio);
CREATE INDEX IX_TB_SY_MNT_ESTRESSE_USUARIO_DATA ON dbo.TB_SY_MNT_ESTRESSE (id_usuario, dt_registro);
CREATE INDEX IX_TB_SY_FEEDBACK_USUARIO_DATA ON dbo.TB_SY_FEEDBACK (id_usuario, dt_registro);
CREATE INDEX IX_TB_SY_APLICACAO_TESTE_USUARIO_DATA ON dbo.TB_SY_APLICACAO_TESTE (id_usuario, dt_aplicacao);
CREATE INDEX IX_TB_SY_RESPOSTA_TESTE_USUARIO_APLICACAO ON dbo.TB_SY_RESPOSTA_TESTE_USUARIO (id_aplicacao);
CREATE INDEX IX_TB_SY_A_ESTRESSE_GATILHO_GATILHO ON dbo.TB_SY_A_ESTRESSE_GATILHO (id_gatilho);
GO
